blank_issues_enabled: true
contact_links:
  - name: OceanEmbed-X Support & Questions
    url: https://github.com/Abdulbasith0512/OceanEmbed-Y/discussions
    about: Ask questions or discuss features with the community.
